// Code generated by go-swagger; DO NOT EDIT.

package access_resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// DeleteResourceReader is a Reader for the DeleteResource structure.
type DeleteResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteResourceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteResourceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteResourceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteResourceNoContent creates a DeleteResourceNoContent with default headers values
func NewDeleteResourceNoContent() *DeleteResourceNoContent {
	return &DeleteResourceNoContent{}
}

/*DeleteResourceNoContent handles this case with default header values.

Resource deleted
*/
type DeleteResourceNoContent struct {
}

func (o *DeleteResourceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /access_resources/{id}][%d] deleteResourceNoContent ", 204)
}

func (o *DeleteResourceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteResourceUnauthorized creates a DeleteResourceUnauthorized with default headers values
func NewDeleteResourceUnauthorized() *DeleteResourceUnauthorized {
	return &DeleteResourceUnauthorized{}
}

/*DeleteResourceUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type DeleteResourceUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *DeleteResourceUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /access_resources/{id}][%d] deleteResourceUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteResourceUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *DeleteResourceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResourceNotFound creates a DeleteResourceNotFound with default headers values
func NewDeleteResourceNotFound() *DeleteResourceNotFound {
	return &DeleteResourceNotFound{}
}

/*DeleteResourceNotFound handles this case with default header values.

resource not found
*/
type DeleteResourceNotFound struct {
}

func (o *DeleteResourceNotFound) Error() string {
	return fmt.Sprintf("[DELETE /access_resources/{id}][%d] deleteResourceNotFound ", 404)
}

func (o *DeleteResourceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
