// Code generated by go-swagger; DO NOT EDIT.

package access_resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEditResourceParams creates a new EditResourceParams object
// with the default values initialized.
func NewEditResourceParams() *EditResourceParams {
	var ()
	return &EditResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEditResourceParamsWithTimeout creates a new EditResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEditResourceParamsWithTimeout(timeout time.Duration) *EditResourceParams {
	var ()
	return &EditResourceParams{

		timeout: timeout,
	}
}

// NewEditResourceParamsWithContext creates a new EditResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewEditResourceParamsWithContext(ctx context.Context) *EditResourceParams {
	var ()
	return &EditResourceParams{

		Context: ctx,
	}
}

// NewEditResourceParamsWithHTTPClient creates a new EditResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEditResourceParamsWithHTTPClient(client *http.Client) *EditResourceParams {
	var ()
	return &EditResourceParams{
		HTTPClient: client,
	}
}

/*EditResourceParams contains all the parameters to send to the API endpoint
for the edit resource operation typically these are written to a http.Request
*/
type EditResourceParams struct {

	/*ID
	  The ID of the resource to edit

	*/
	ID strfmt.UUID
	/*Resource
	  Resource information to modify

	*/
	Resource EditResourceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the edit resource params
func (o *EditResourceParams) WithTimeout(timeout time.Duration) *EditResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edit resource params
func (o *EditResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edit resource params
func (o *EditResourceParams) WithContext(ctx context.Context) *EditResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edit resource params
func (o *EditResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edit resource params
func (o *EditResourceParams) WithHTTPClient(client *http.Client) *EditResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edit resource params
func (o *EditResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the edit resource params
func (o *EditResourceParams) WithID(id strfmt.UUID) *EditResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the edit resource params
func (o *EditResourceParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithResource adds the resource to the edit resource params
func (o *EditResourceParams) WithResource(resource EditResourceBody) *EditResourceParams {
	o.SetResource(resource)
	return o
}

// SetResource adds the resource to the edit resource params
func (o *EditResourceParams) SetResource(resource EditResourceBody) {
	o.Resource = resource
}

// WriteToRequest writes these params to a swagger request
func (o *EditResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Resource); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
