// Code generated by go-swagger; DO NOT EDIT.

package access_resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetResourceParams creates a new GetResourceParams object
// with the default values initialized.
func NewGetResourceParams() *GetResourceParams {
	var ()
	return &GetResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetResourceParamsWithTimeout creates a new GetResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetResourceParamsWithTimeout(timeout time.Duration) *GetResourceParams {
	var ()
	return &GetResourceParams{

		timeout: timeout,
	}
}

// NewGetResourceParamsWithContext creates a new GetResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetResourceParamsWithContext(ctx context.Context) *GetResourceParams {
	var ()
	return &GetResourceParams{

		Context: ctx,
	}
}

// NewGetResourceParamsWithHTTPClient creates a new GetResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetResourceParamsWithHTTPClient(client *http.Client) *GetResourceParams {
	var ()
	return &GetResourceParams{
		HTTPClient: client,
	}
}

/*GetResourceParams contains all the parameters to send to the API endpoint
for the get resource operation typically these are written to a http.Request
*/
type GetResourceParams struct {

	/*ID
	  The ID of the resource to retrieve

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get resource params
func (o *GetResourceParams) WithTimeout(timeout time.Duration) *GetResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get resource params
func (o *GetResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get resource params
func (o *GetResourceParams) WithContext(ctx context.Context) *GetResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get resource params
func (o *GetResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get resource params
func (o *GetResourceParams) WithHTTPClient(client *http.Client) *GetResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get resource params
func (o *GetResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get resource params
func (o *GetResourceParams) WithID(id int64) *GetResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get resource params
func (o *GetResourceParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
