// Code generated by go-swagger; DO NOT EDIT.

package access_resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// ListResourcesReader is a Reader for the ListResources structure.
type ListResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListResourcesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListResourcesOK creates a ListResourcesOK with default headers values
func NewListResourcesOK() *ListResourcesOK {
	return &ListResourcesOK{}
}

/*ListResourcesOK handles this case with default header values.

successful operation
*/
type ListResourcesOK struct {
	/*Total number of items (for pagination)
	 */
	Total int64

	Payload []*ListResourcesOKBodyItems0
}

func (o *ListResourcesOK) Error() string {
	return fmt.Sprintf("[GET /access_resources][%d] listResourcesOK  %+v", 200, o.Payload)
}

func (o *ListResourcesOK) GetPayload() []*ListResourcesOKBodyItems0 {
	return o.Payload
}

func (o *ListResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header total
	total, err := swag.ConvertInt64(response.GetHeader("total"))
	if err != nil {
		return errors.InvalidType("total", "header", "int64", response.GetHeader("total"))
	}
	o.Total = total

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListResourcesUnauthorized creates a ListResourcesUnauthorized with default headers values
func NewListResourcesUnauthorized() *ListResourcesUnauthorized {
	return &ListResourcesUnauthorized{}
}

/*ListResourcesUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type ListResourcesUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *ListResourcesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /access_resources][%d] listResourcesUnauthorized  %+v", 401, o.Payload)
}

func (o *ListResourcesUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *ListResourcesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListResourcesOKBodyItems0 list resources o k body items0
swagger:model ListResourcesOKBodyItems0
*/
type ListResourcesOKBodyItems0 struct {
	models.AccessResource

	// access proxy id
	// Format: uuid
	AccessProxyID strfmt.UUID `json:"access_proxy_id,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *ListResourcesOKBodyItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 models.AccessResource
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	o.AccessResource = aO0

	// AO1
	var dataAO1 struct {
		AccessProxyID strfmt.UUID `json:"access_proxy_id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.AccessProxyID = dataAO1.AccessProxyID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o ListResourcesOKBodyItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(o.AccessResource)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		AccessProxyID strfmt.UUID `json:"access_proxy_id,omitempty"`
	}

	dataAO1.AccessProxyID = o.AccessProxyID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this list resources o k body items0
func (o *ListResourcesOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.AccessResource
	if err := o.AccessResource.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateAccessProxyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListResourcesOKBodyItems0) validateAccessProxyID(formats strfmt.Registry) error {

	if swag.IsZero(o.AccessProxyID) { // not required
		return nil
	}

	if err := validate.FormatOf("access_proxy_id", "body", "uuid", o.AccessProxyID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ListResourcesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListResourcesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListResourcesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
