// Code generated by go-swagger; DO NOT EDIT.

package access_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateProxyParams creates a new CreateProxyParams object
// with the default values initialized.
func NewCreateProxyParams() *CreateProxyParams {
	var ()
	return &CreateProxyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateProxyParamsWithTimeout creates a new CreateProxyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateProxyParamsWithTimeout(timeout time.Duration) *CreateProxyParams {
	var ()
	return &CreateProxyParams{

		timeout: timeout,
	}
}

// NewCreateProxyParamsWithContext creates a new CreateProxyParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateProxyParamsWithContext(ctx context.Context) *CreateProxyParams {
	var ()
	return &CreateProxyParams{

		Context: ctx,
	}
}

// NewCreateProxyParamsWithHTTPClient creates a new CreateProxyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateProxyParamsWithHTTPClient(client *http.Client) *CreateProxyParams {
	var ()
	return &CreateProxyParams{
		HTTPClient: client,
	}
}

/*CreateProxyParams contains all the parameters to send to the API endpoint
for the create proxy operation typically these are written to a http.Request
*/
type CreateProxyParams struct {

	/*Proxy
	  Information about the proxy to create

	*/
	Proxy CreateProxyBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create proxy params
func (o *CreateProxyParams) WithTimeout(timeout time.Duration) *CreateProxyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create proxy params
func (o *CreateProxyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create proxy params
func (o *CreateProxyParams) WithContext(ctx context.Context) *CreateProxyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create proxy params
func (o *CreateProxyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create proxy params
func (o *CreateProxyParams) WithHTTPClient(client *http.Client) *CreateProxyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create proxy params
func (o *CreateProxyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProxy adds the proxy to the create proxy params
func (o *CreateProxyParams) WithProxy(proxy CreateProxyBody) *CreateProxyParams {
	o.SetProxy(proxy)
	return o
}

// SetProxy adds the proxy to the create proxy params
func (o *CreateProxyParams) SetProxy(proxy CreateProxyBody) {
	o.Proxy = proxy
}

// WriteToRequest writes these params to a swagger request
func (o *CreateProxyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Proxy); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
