// Code generated by go-swagger; DO NOT EDIT.

package access_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// CreateProxyReader is a Reader for the CreateProxy structure.
type CreateProxyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProxyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateProxyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateProxyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateProxyCreated creates a CreateProxyCreated with default headers values
func NewCreateProxyCreated() *CreateProxyCreated {
	return &CreateProxyCreated{}
}

/*CreateProxyCreated handles this case with default header values.

Proxy created
*/
type CreateProxyCreated struct {
	Payload *CreateProxyCreatedBody
}

func (o *CreateProxyCreated) Error() string {
	return fmt.Sprintf("[POST /access_proxies][%d] createProxyCreated  %+v", 201, o.Payload)
}

func (o *CreateProxyCreated) GetPayload() *CreateProxyCreatedBody {
	return o.Payload
}

func (o *CreateProxyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateProxyCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProxyUnauthorized creates a CreateProxyUnauthorized with default headers values
func NewCreateProxyUnauthorized() *CreateProxyUnauthorized {
	return &CreateProxyUnauthorized{}
}

/*CreateProxyUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type CreateProxyUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *CreateProxyUnauthorized) Error() string {
	return fmt.Sprintf("[POST /access_proxies][%d] createProxyUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateProxyUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *CreateProxyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateProxyBody create proxy body
swagger:model CreateProxyBody
*/
type CreateProxyBody struct {

	// host
	Host string `json:"host,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// port
	Port string `json:"port,omitempty"`
}

// Validate validates this create proxy body
func (o *CreateProxyBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateProxyBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateProxyBody) UnmarshalBinary(b []byte) error {
	var res CreateProxyBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateProxyCreatedBody create proxy created body
swagger:model CreateProxyCreatedBody
*/
type CreateProxyCreatedBody struct {

	// enrollment url
	EnrollmentURL string `json:"enrollment_url,omitempty"`

	// host
	Host string `json:"host,omitempty"`

	// id
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`

	// status
	// Enum: [proxy_pending proxy_enabled]
	Status string `json:"status,omitempty"`
}

// Validate validates this create proxy created body
func (o *CreateProxyCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateProxyCreatedBody) validateID(formats strfmt.Registry) error {

	if swag.IsZero(o.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("createProxyCreated"+"."+"id", "body", "uuid", o.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

var createProxyCreatedBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["proxy_pending","proxy_enabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createProxyCreatedBodyTypeStatusPropEnum = append(createProxyCreatedBodyTypeStatusPropEnum, v)
	}
}

const (

	// CreateProxyCreatedBodyStatusProxyPending captures enum value "proxy_pending"
	CreateProxyCreatedBodyStatusProxyPending string = "proxy_pending"

	// CreateProxyCreatedBodyStatusProxyEnabled captures enum value "proxy_enabled"
	CreateProxyCreatedBodyStatusProxyEnabled string = "proxy_enabled"
)

// prop value enum
func (o *CreateProxyCreatedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, createProxyCreatedBodyTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (o *CreateProxyCreatedBody) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("createProxyCreated"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateProxyCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateProxyCreatedBody) UnmarshalBinary(b []byte) error {
	var res CreateProxyCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
