// Code generated by go-swagger; DO NOT EDIT.

package access_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// DeleteProxyReader is a Reader for the DeleteProxy structure.
type DeleteProxyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProxyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteProxyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteProxyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteProxyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteProxyNoContent creates a DeleteProxyNoContent with default headers values
func NewDeleteProxyNoContent() *DeleteProxyNoContent {
	return &DeleteProxyNoContent{}
}

/*DeleteProxyNoContent handles this case with default header values.

Proxy deleted
*/
type DeleteProxyNoContent struct {
}

func (o *DeleteProxyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /access_proxies/{id}][%d] deleteProxyNoContent ", 204)
}

func (o *DeleteProxyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProxyUnauthorized creates a DeleteProxyUnauthorized with default headers values
func NewDeleteProxyUnauthorized() *DeleteProxyUnauthorized {
	return &DeleteProxyUnauthorized{}
}

/*DeleteProxyUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type DeleteProxyUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *DeleteProxyUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /access_proxies/{id}][%d] deleteProxyUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteProxyUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *DeleteProxyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProxyNotFound creates a DeleteProxyNotFound with default headers values
func NewDeleteProxyNotFound() *DeleteProxyNotFound {
	return &DeleteProxyNotFound{}
}

/*DeleteProxyNotFound handles this case with default header values.

Proxy not found
*/
type DeleteProxyNotFound struct {
}

func (o *DeleteProxyNotFound) Error() string {
	return fmt.Sprintf("[DELETE /access_proxies/{id}][%d] deleteProxyNotFound ", 404)
}

func (o *DeleteProxyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
