// Code generated by go-swagger; DO NOT EDIT.

package access_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteProxyParams creates a new DeleteProxyParams object
// with the default values initialized.
func NewDeleteProxyParams() *DeleteProxyParams {
	var ()
	return &DeleteProxyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProxyParamsWithTimeout creates a new DeleteProxyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteProxyParamsWithTimeout(timeout time.Duration) *DeleteProxyParams {
	var ()
	return &DeleteProxyParams{

		timeout: timeout,
	}
}

// NewDeleteProxyParamsWithContext creates a new DeleteProxyParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteProxyParamsWithContext(ctx context.Context) *DeleteProxyParams {
	var ()
	return &DeleteProxyParams{

		Context: ctx,
	}
}

// NewDeleteProxyParamsWithHTTPClient creates a new DeleteProxyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteProxyParamsWithHTTPClient(client *http.Client) *DeleteProxyParams {
	var ()
	return &DeleteProxyParams{
		HTTPClient: client,
	}
}

/*DeleteProxyParams contains all the parameters to send to the API endpoint
for the delete proxy operation typically these are written to a http.Request
*/
type DeleteProxyParams struct {

	/*ID
	  The ID of the proxy to delete

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete proxy params
func (o *DeleteProxyParams) WithTimeout(timeout time.Duration) *DeleteProxyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete proxy params
func (o *DeleteProxyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete proxy params
func (o *DeleteProxyParams) WithContext(ctx context.Context) *DeleteProxyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete proxy params
func (o *DeleteProxyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete proxy params
func (o *DeleteProxyParams) WithHTTPClient(client *http.Client) *DeleteProxyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete proxy params
func (o *DeleteProxyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete proxy params
func (o *DeleteProxyParams) WithID(id strfmt.UUID) *DeleteProxyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete proxy params
func (o *DeleteProxyParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProxyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
