// Code generated by go-swagger; DO NOT EDIT.

package access_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// EditProxyReader is a Reader for the EditProxy structure.
type EditProxyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EditProxyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEditProxyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewEditProxyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEditProxyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEditProxyOK creates a EditProxyOK with default headers values
func NewEditProxyOK() *EditProxyOK {
	return &EditProxyOK{}
}

/*EditProxyOK handles this case with default header values.

Proxy edited
*/
type EditProxyOK struct {
	Payload *EditProxyOKBody
}

func (o *EditProxyOK) Error() string {
	return fmt.Sprintf("[PATCH /access_proxies/{id}][%d] editProxyOK  %+v", 200, o.Payload)
}

func (o *EditProxyOK) GetPayload() *EditProxyOKBody {
	return o.Payload
}

func (o *EditProxyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(EditProxyOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditProxyUnauthorized creates a EditProxyUnauthorized with default headers values
func NewEditProxyUnauthorized() *EditProxyUnauthorized {
	return &EditProxyUnauthorized{}
}

/*EditProxyUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type EditProxyUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *EditProxyUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /access_proxies/{id}][%d] editProxyUnauthorized  %+v", 401, o.Payload)
}

func (o *EditProxyUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *EditProxyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditProxyNotFound creates a EditProxyNotFound with default headers values
func NewEditProxyNotFound() *EditProxyNotFound {
	return &EditProxyNotFound{}
}

/*EditProxyNotFound handles this case with default header values.

Proxy not found
*/
type EditProxyNotFound struct {
}

func (o *EditProxyNotFound) Error() string {
	return fmt.Sprintf("[PATCH /access_proxies/{id}][%d] editProxyNotFound ", 404)
}

func (o *EditProxyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*AccessResourcesItems0 access resources items0
swagger:model AccessResourcesItems0
*/
type AccessResourcesItems0 struct {

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// id
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// updated at
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this access resources items0
func (o *AccessResourcesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AccessResourcesItems0) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *AccessResourcesItems0) validateID(formats strfmt.Registry) error {

	if swag.IsZero(o.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", o.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *AccessResourcesItems0) validateUpdatedAt(formats strfmt.Registry) error {

	if swag.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AccessResourcesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AccessResourcesItems0) UnmarshalBinary(b []byte) error {
	var res AccessResourcesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*EditProxyBody edit proxy body
swagger:model EditProxyBody
*/
type EditProxyBody struct {

	// access proxy
	AccessProxy struct {
		models.AccessProxy

		// access resources
		AccessResources []*AccessResourcesItems0 `json:"access_resources"`

		// proxy version
		ProxyVersion string `json:"proxy_version,omitempty"`
	} `json:"access_proxy,omitempty"`
}

// Validate validates this edit proxy body
func (o *EditProxyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAccessProxy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EditProxyBody) validateAccessProxy(formats strfmt.Registry) error {

	if swag.IsZero(o.AccessProxy) { // not required
		return nil
	}

	for i := 0; i < len(o.AccessProxy.AccessResources); i++ {
		if swag.IsZero(o.AccessProxy.AccessResources[i]) { // not required
			continue
		}

		if o.AccessProxy.AccessResources[i] != nil {
			if err := o.AccessProxy.AccessResources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("proxy" + "." + "access_proxy" + "." + "access_resources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *EditProxyBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EditProxyBody) UnmarshalBinary(b []byte) error {
	var res EditProxyBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*EditProxyOKBody edit proxy o k body
swagger:model EditProxyOKBody
*/
type EditProxyOKBody struct {
	models.AccessProxy

	EditProxyOKBodyAllOf1

	// access resources
	AccessResources []*AccessResourcesItems0 `json:"access_resources"`

	// proxy version
	ProxyVersion string `json:"proxy_version,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *EditProxyOKBody) UnmarshalJSON(raw []byte) error {
	// EditProxyOKBodyAO0
	var editProxyOKBodyAO0 models.AccessProxy
	if err := swag.ReadJSON(raw, &editProxyOKBodyAO0); err != nil {
		return err
	}
	o.AccessProxy = editProxyOKBodyAO0

	// EditProxyOKBodyAO1
	var editProxyOKBodyAO1 EditProxyOKBodyAllOf1
	if err := swag.ReadJSON(raw, &editProxyOKBodyAO1); err != nil {
		return err
	}
	o.EditProxyOKBodyAllOf1 = editProxyOKBodyAO1

	// now for regular properties
	var propsEditProxyOKBody struct {
		AccessResources []*AccessResourcesItems0 `json:"access_resources"`

		ProxyVersion string `json:"proxy_version,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsEditProxyOKBody); err != nil {
		return err
	}
	o.AccessResources = propsEditProxyOKBody.AccessResources

	o.ProxyVersion = propsEditProxyOKBody.ProxyVersion

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o EditProxyOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	editProxyOKBodyAO0, err := swag.WriteJSON(o.AccessProxy)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, editProxyOKBodyAO0)

	editProxyOKBodyAO1, err := swag.WriteJSON(o.EditProxyOKBodyAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, editProxyOKBodyAO1)

	// now for regular properties
	var propsEditProxyOKBody struct {
		AccessResources []*AccessResourcesItems0 `json:"access_resources"`

		ProxyVersion string `json:"proxy_version,omitempty"`
	}
	propsEditProxyOKBody.AccessResources = o.AccessResources

	propsEditProxyOKBody.ProxyVersion = o.ProxyVersion

	jsonDataPropsEditProxyOKBody, errEditProxyOKBody := swag.WriteJSON(propsEditProxyOKBody)
	if errEditProxyOKBody != nil {
		return nil, errEditProxyOKBody
	}
	_parts = append(_parts, jsonDataPropsEditProxyOKBody)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this edit proxy o k body
func (o *EditProxyOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.AccessProxy
	if err := o.AccessProxy.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with EditProxyOKBodyAllOf1

	if err := o.validateAccessResources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EditProxyOKBody) validateAccessResources(formats strfmt.Registry) error {

	if swag.IsZero(o.AccessResources) { // not required
		return nil
	}

	for i := 0; i < len(o.AccessResources); i++ {
		if swag.IsZero(o.AccessResources[i]) { // not required
			continue
		}

		if o.AccessResources[i] != nil {
			if err := o.AccessResources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("editProxyOK" + "." + "access_resources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *EditProxyOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EditProxyOKBody) UnmarshalBinary(b []byte) error {
	var res EditProxyOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*EditProxyOKBodyAllOf1 edit proxy o k body all of1
swagger:model EditProxyOKBodyAllOf1
*/
type EditProxyOKBodyAllOf1 interface{}
