// Code generated by go-swagger; DO NOT EDIT.

package access_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// GetProxyReader is a Reader for the GetProxy structure.
type GetProxyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProxyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProxyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetProxyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProxyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProxyOK creates a GetProxyOK with default headers values
func NewGetProxyOK() *GetProxyOK {
	return &GetProxyOK{}
}

/*GetProxyOK handles this case with default header values.

Proxy info
*/
type GetProxyOK struct {
	Payload *GetProxyOKBody
}

func (o *GetProxyOK) Error() string {
	return fmt.Sprintf("[GET /access_proxies/{id}][%d] getProxyOK  %+v", 200, o.Payload)
}

func (o *GetProxyOK) GetPayload() *GetProxyOKBody {
	return o.Payload
}

func (o *GetProxyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetProxyOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProxyUnauthorized creates a GetProxyUnauthorized with default headers values
func NewGetProxyUnauthorized() *GetProxyUnauthorized {
	return &GetProxyUnauthorized{}
}

/*GetProxyUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type GetProxyUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *GetProxyUnauthorized) Error() string {
	return fmt.Sprintf("[GET /access_proxies/{id}][%d] getProxyUnauthorized  %+v", 401, o.Payload)
}

func (o *GetProxyUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *GetProxyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProxyNotFound creates a GetProxyNotFound with default headers values
func NewGetProxyNotFound() *GetProxyNotFound {
	return &GetProxyNotFound{}
}

/*GetProxyNotFound handles this case with default header values.

Proxy not found
*/
type GetProxyNotFound struct {
}

func (o *GetProxyNotFound) Error() string {
	return fmt.Sprintf("[GET /access_proxies/{id}][%d] getProxyNotFound ", 404)
}

func (o *GetProxyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetProxyOKBody get proxy o k body
swagger:model GetProxyOKBody
*/
type GetProxyOKBody struct {
	models.AccessProxy

	// access resources
	AccessResources []*AccessResourcesItems0 `json:"access_resources"`

	// proxy version
	ProxyVersion string `json:"proxy_version,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetProxyOKBody) UnmarshalJSON(raw []byte) error {
	// GetProxyOKBodyAO0
	var getProxyOKBodyAO0 models.AccessProxy
	if err := swag.ReadJSON(raw, &getProxyOKBodyAO0); err != nil {
		return err
	}
	o.AccessProxy = getProxyOKBodyAO0

	// GetProxyOKBodyAO1
	var dataGetProxyOKBodyAO1 struct {
		AccessResources []*AccessResourcesItems0 `json:"access_resources"`

		ProxyVersion string `json:"proxy_version,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetProxyOKBodyAO1); err != nil {
		return err
	}

	o.AccessResources = dataGetProxyOKBodyAO1.AccessResources

	o.ProxyVersion = dataGetProxyOKBodyAO1.ProxyVersion

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetProxyOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getProxyOKBodyAO0, err := swag.WriteJSON(o.AccessProxy)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getProxyOKBodyAO0)

	var dataGetProxyOKBodyAO1 struct {
		AccessResources []*AccessResourcesItems0 `json:"access_resources"`

		ProxyVersion string `json:"proxy_version,omitempty"`
	}

	dataGetProxyOKBodyAO1.AccessResources = o.AccessResources

	dataGetProxyOKBodyAO1.ProxyVersion = o.ProxyVersion

	jsonDataGetProxyOKBodyAO1, errGetProxyOKBodyAO1 := swag.WriteJSON(dataGetProxyOKBodyAO1)
	if errGetProxyOKBodyAO1 != nil {
		return nil, errGetProxyOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetProxyOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get proxy o k body
func (o *GetProxyOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.AccessProxy
	if err := o.AccessProxy.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateAccessResources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetProxyOKBody) validateAccessResources(formats strfmt.Registry) error {

	if swag.IsZero(o.AccessResources) { // not required
		return nil
	}

	for i := 0; i < len(o.AccessResources); i++ {
		if swag.IsZero(o.AccessResources[i]) { // not required
			continue
		}

		if o.AccessResources[i] != nil {
			if err := o.AccessResources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getProxyOK" + "." + "access_resources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetProxyOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetProxyOKBody) UnmarshalBinary(b []byte) error {
	var res GetProxyOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
