// Code generated by go-swagger; DO NOT EDIT.

package access_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// ListProxiesReader is a Reader for the ListProxies structure.
type ListProxiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProxiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProxiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListProxiesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListProxiesOK creates a ListProxiesOK with default headers values
func NewListProxiesOK() *ListProxiesOK {
	return &ListProxiesOK{}
}

/*ListProxiesOK handles this case with default header values.

successful operation
*/
type ListProxiesOK struct {
	/*Total number of items (for pagination)
	 */
	Total int64

	Payload []*ListProxiesOKBodyItems0
}

func (o *ListProxiesOK) Error() string {
	return fmt.Sprintf("[GET /access_proxies][%d] listProxiesOK  %+v", 200, o.Payload)
}

func (o *ListProxiesOK) GetPayload() []*ListProxiesOKBodyItems0 {
	return o.Payload
}

func (o *ListProxiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header total
	total, err := swag.ConvertInt64(response.GetHeader("total"))
	if err != nil {
		return errors.InvalidType("total", "header", "int64", response.GetHeader("total"))
	}
	o.Total = total

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProxiesUnauthorized creates a ListProxiesUnauthorized with default headers values
func NewListProxiesUnauthorized() *ListProxiesUnauthorized {
	return &ListProxiesUnauthorized{}
}

/*ListProxiesUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type ListProxiesUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *ListProxiesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /access_proxies][%d] listProxiesUnauthorized  %+v", 401, o.Payload)
}

func (o *ListProxiesUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *ListProxiesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListProxiesOKBodyItems0 list proxies o k body items0
swagger:model ListProxiesOKBodyItems0
*/
type ListProxiesOKBodyItems0 struct {
	models.AccessProxy

	// access resources count
	AccessResourcesCount int64 `json:"access_resources_count,omitempty"`

	// enrollment count
	EnrollmentCount int64 `json:"enrollment_count,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *ListProxiesOKBodyItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 models.AccessProxy
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	o.AccessProxy = aO0

	// AO1
	var dataAO1 struct {
		AccessResourcesCount int64 `json:"access_resources_count,omitempty"`

		EnrollmentCount int64 `json:"enrollment_count,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.AccessResourcesCount = dataAO1.AccessResourcesCount

	o.EnrollmentCount = dataAO1.EnrollmentCount

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o ListProxiesOKBodyItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(o.AccessProxy)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		AccessResourcesCount int64 `json:"access_resources_count,omitempty"`

		EnrollmentCount int64 `json:"enrollment_count,omitempty"`
	}

	dataAO1.AccessResourcesCount = o.AccessResourcesCount

	dataAO1.EnrollmentCount = o.EnrollmentCount

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this list proxies o k body items0
func (o *ListProxiesOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.AccessProxy
	if err := o.AccessProxy.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *ListProxiesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListProxiesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListProxiesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
