// Code generated by go-swagger; DO NOT EDIT.

package access_proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListProxiesParams creates a new ListProxiesParams object
// with the default values initialized.
func NewListProxiesParams() *ListProxiesParams {
	var ()
	return &ListProxiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListProxiesParamsWithTimeout creates a new ListProxiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListProxiesParamsWithTimeout(timeout time.Duration) *ListProxiesParams {
	var ()
	return &ListProxiesParams{

		timeout: timeout,
	}
}

// NewListProxiesParamsWithContext creates a new ListProxiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListProxiesParamsWithContext(ctx context.Context) *ListProxiesParams {
	var ()
	return &ListProxiesParams{

		Context: ctx,
	}
}

// NewListProxiesParamsWithHTTPClient creates a new ListProxiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListProxiesParamsWithHTTPClient(client *http.Client) *ListProxiesParams {
	var ()
	return &ListProxiesParams{
		HTTPClient: client,
	}
}

/*ListProxiesParams contains all the parameters to send to the API endpoint
for the list proxies operation typically these are written to a http.Request
*/
type ListProxiesParams struct {

	/*Page
	  Page number

	*/
	Page *int64
	/*PerPage
	  Number of items to return per page

	*/
	PerPage *int64
	/*Sort
	  Sort results

	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list proxies params
func (o *ListProxiesParams) WithTimeout(timeout time.Duration) *ListProxiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list proxies params
func (o *ListProxiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list proxies params
func (o *ListProxiesParams) WithContext(ctx context.Context) *ListProxiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list proxies params
func (o *ListProxiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list proxies params
func (o *ListProxiesParams) WithHTTPClient(client *http.Client) *ListProxiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list proxies params
func (o *ListProxiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the list proxies params
func (o *ListProxiesParams) WithPage(page *int64) *ListProxiesParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the list proxies params
func (o *ListProxiesParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the list proxies params
func (o *ListProxiesParams) WithPerPage(perPage *int64) *ListProxiesParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the list proxies params
func (o *ListProxiesParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WithSort adds the sort to the list proxies params
func (o *ListProxiesParams) WithSort(sort *string) *ListProxiesParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the list proxies params
func (o *ListProxiesParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *ListProxiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage int64
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}

	}

	if o.Sort != nil {

		// query param sort
		var qrSort string
		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {
			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
