// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDeviceParams creates a new GetDeviceParams object
// with the default values initialized.
func NewGetDeviceParams() *GetDeviceParams {
	var ()
	return &GetDeviceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeviceParamsWithTimeout creates a new GetDeviceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDeviceParamsWithTimeout(timeout time.Duration) *GetDeviceParams {
	var ()
	return &GetDeviceParams{

		timeout: timeout,
	}
}

// NewGetDeviceParamsWithContext creates a new GetDeviceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDeviceParamsWithContext(ctx context.Context) *GetDeviceParams {
	var ()
	return &GetDeviceParams{

		Context: ctx,
	}
}

// NewGetDeviceParamsWithHTTPClient creates a new GetDeviceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDeviceParamsWithHTTPClient(client *http.Client) *GetDeviceParams {
	var ()
	return &GetDeviceParams{
		HTTPClient: client,
	}
}

/*GetDeviceParams contains all the parameters to send to the API endpoint
for the get device operation typically these are written to a http.Request
*/
type GetDeviceParams struct {

	/*ID
	  The ID of the device to retrieve

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get device params
func (o *GetDeviceParams) WithTimeout(timeout time.Duration) *GetDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get device params
func (o *GetDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get device params
func (o *GetDeviceParams) WithContext(ctx context.Context) *GetDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get device params
func (o *GetDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get device params
func (o *GetDeviceParams) WithHTTPClient(client *http.Client) *GetDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get device params
func (o *GetDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get device params
func (o *GetDeviceParams) WithID(id int64) *GetDeviceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get device params
func (o *GetDeviceParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
