// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// ListDevicesReader is a Reader for the ListDevices structure.
type ListDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListDevicesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListDevicesOK creates a ListDevicesOK with default headers values
func NewListDevicesOK() *ListDevicesOK {
	return &ListDevicesOK{}
}

/*ListDevicesOK handles this case with default header values.

successful operation
*/
type ListDevicesOK struct {
	/*Total number of items (for pagination)
	 */
	Total int64

	Payload []*models.Device
}

func (o *ListDevicesOK) Error() string {
	return fmt.Sprintf("[GET /devices][%d] listDevicesOK  %+v", 200, o.Payload)
}

func (o *ListDevicesOK) GetPayload() []*models.Device {
	return o.Payload
}

func (o *ListDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header total
	total, err := swag.ConvertInt64(response.GetHeader("total"))
	if err != nil {
		return errors.InvalidType("total", "header", "int64", response.GetHeader("total"))
	}
	o.Total = total

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDevicesUnauthorized creates a ListDevicesUnauthorized with default headers values
func NewListDevicesUnauthorized() *ListDevicesUnauthorized {
	return &ListDevicesUnauthorized{}
}

/*ListDevicesUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type ListDevicesUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *ListDevicesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /devices][%d] listDevicesUnauthorized  %+v", 401, o.Payload)
}

func (o *ListDevicesUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *ListDevicesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
