env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - swagger generate client -f swagger.yml
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -s -w -X main.GitCommit={{.ShortCommit}} -X main.BuildDate={{.Date}} -X main.Version={{.Version}} -X main.GitState=clean
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
