env:
  - GO111MODULE=on
before:
  hooks:
    - swagger generate client -f swagger.yml
    - go mod tidy
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X main.GitCommit={{.ShortCommit}} -X main.BuildDate={{.Date}} -X main.Version={{.Version}} -X main.GitState=clean
    hooks:
      pre: ./scripts/generate-completions.sh
archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
nfpms:
  -
    vendor: Fyde, Inc.
    homepage: https://fyde.github.io/docs/fyde-cli/
    description: Command-line client for Fyde Enterprise Console APIs
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    contents:
      - src: "dist/completions/fyde-cli.bash"
        dst: "/usr/share/bash-completion/completions/fyde-cli"
      - src: "dist/completions/fyde-cli.zsh"
        dst: "/usr/share/zsh/site-functions/_fyde-cli"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
