// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEditGroupParams creates a new EditGroupParams object
// with the default values initialized.
func NewEditGroupParams() *EditGroupParams {
	var ()
	return &EditGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEditGroupParamsWithTimeout creates a new EditGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEditGroupParamsWithTimeout(timeout time.Duration) *EditGroupParams {
	var ()
	return &EditGroupParams{

		timeout: timeout,
	}
}

// NewEditGroupParamsWithContext creates a new EditGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewEditGroupParamsWithContext(ctx context.Context) *EditGroupParams {
	var ()
	return &EditGroupParams{

		Context: ctx,
	}
}

// NewEditGroupParamsWithHTTPClient creates a new EditGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEditGroupParamsWithHTTPClient(client *http.Client) *EditGroupParams {
	var ()
	return &EditGroupParams{
		HTTPClient: client,
	}
}

/*EditGroupParams contains all the parameters to send to the API endpoint
for the edit group operation typically these are written to a http.Request
*/
type EditGroupParams struct {

	/*Group
	  Group information to modify

	*/
	Group EditGroupBody
	/*ID
	  The ID of the group to edit

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the edit group params
func (o *EditGroupParams) WithTimeout(timeout time.Duration) *EditGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edit group params
func (o *EditGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edit group params
func (o *EditGroupParams) WithContext(ctx context.Context) *EditGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edit group params
func (o *EditGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edit group params
func (o *EditGroupParams) WithHTTPClient(client *http.Client) *EditGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edit group params
func (o *EditGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the edit group params
func (o *EditGroupParams) WithGroup(group EditGroupBody) *EditGroupParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the edit group params
func (o *EditGroupParams) SetGroup(group EditGroupBody) {
	o.Group = group
}

// WithID adds the id to the edit group params
func (o *EditGroupParams) WithID(id int64) *EditGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the edit group params
func (o *EditGroupParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EditGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Group); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
