// Code generated by go-swagger; DO NOT EDIT.

package access_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/oNaiPs/fyde-cli/models"
)

// ListPoliciesReader is a Reader for the ListPolicies structure.
type ListPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListPoliciesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListPoliciesOK creates a ListPoliciesOK with default headers values
func NewListPoliciesOK() *ListPoliciesOK {
	return &ListPoliciesOK{}
}

/*ListPoliciesOK handles this case with default header values.

successful operation
*/
type ListPoliciesOK struct {
	/*Total number of items (for pagination)
	 */
	Total int64

	Payload []*ListPoliciesOKBodyItems0
}

func (o *ListPoliciesOK) Error() string {
	return fmt.Sprintf("[GET /access_policies][%d] listPoliciesOK  %+v", 200, o.Payload)
}

func (o *ListPoliciesOK) GetPayload() []*ListPoliciesOKBodyItems0 {
	return o.Payload
}

func (o *ListPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header total
	total, err := swag.ConvertInt64(response.GetHeader("total"))
	if err != nil {
		return errors.InvalidType("total", "header", "int64", response.GetHeader("total"))
	}
	o.Total = total

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPoliciesUnauthorized creates a ListPoliciesUnauthorized with default headers values
func NewListPoliciesUnauthorized() *ListPoliciesUnauthorized {
	return &ListPoliciesUnauthorized{}
}

/*ListPoliciesUnauthorized handles this case with default header values.

unauthorized: invalid credentials or missing authentication headers
*/
type ListPoliciesUnauthorized struct {
	Payload *models.GenericUnauthorizedResponse
}

func (o *ListPoliciesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /access_policies][%d] listPoliciesUnauthorized  %+v", 401, o.Payload)
}

func (o *ListPoliciesUnauthorized) GetPayload() *models.GenericUnauthorizedResponse {
	return o.Payload
}

func (o *ListPoliciesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericUnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListPoliciesOKBodyItems0 list policies o k body items0
swagger:model ListPoliciesOKBodyItems0
*/
type ListPoliciesOKBodyItems0 struct {
	models.AccessPolicy

	// access resources count
	AccessResourcesCount int64 `json:"access_resources_count,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *ListPoliciesOKBodyItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 models.AccessPolicy
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	o.AccessPolicy = aO0

	// AO1
	var dataAO1 struct {
		AccessResourcesCount int64 `json:"access_resources_count,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.AccessResourcesCount = dataAO1.AccessResourcesCount

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o ListPoliciesOKBodyItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(o.AccessPolicy)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		AccessResourcesCount int64 `json:"access_resources_count,omitempty"`
	}

	dataAO1.AccessResourcesCount = o.AccessResourcesCount

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this list policies o k body items0
func (o *ListPoliciesOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.AccessPolicy
	if err := o.AccessPolicy.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *ListPoliciesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListPoliciesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListPoliciesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
