// Code generated by go-swagger; DO NOT EDIT.

package device_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListDeviceEventsParams creates a new ListDeviceEventsParams object
// with the default values initialized.
func NewListDeviceEventsParams() *ListDeviceEventsParams {
	var ()
	return &ListDeviceEventsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListDeviceEventsParamsWithTimeout creates a new ListDeviceEventsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDeviceEventsParamsWithTimeout(timeout time.Duration) *ListDeviceEventsParams {
	var ()
	return &ListDeviceEventsParams{

		timeout: timeout,
	}
}

// NewListDeviceEventsParamsWithContext creates a new ListDeviceEventsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListDeviceEventsParamsWithContext(ctx context.Context) *ListDeviceEventsParams {
	var ()
	return &ListDeviceEventsParams{

		Context: ctx,
	}
}

// NewListDeviceEventsParamsWithHTTPClient creates a new ListDeviceEventsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDeviceEventsParamsWithHTTPClient(client *http.Client) *ListDeviceEventsParams {
	var ()
	return &ListDeviceEventsParams{
		HTTPClient: client,
	}
}

/*ListDeviceEventsParams contains all the parameters to send to the API endpoint
for the list device events operation typically these are written to a http.Request
*/
type ListDeviceEventsParams struct {

	/*EventName
	  Restrict the types of events to return

	*/
	EventName []string
	/*Page
	  Page number

	*/
	Page *int64
	/*PerPage
	  Number of items to return per page

	*/
	PerPage *int64
	/*User
	  Restrict the events to return to the specified user name

	*/
	User *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list device events params
func (o *ListDeviceEventsParams) WithTimeout(timeout time.Duration) *ListDeviceEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list device events params
func (o *ListDeviceEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list device events params
func (o *ListDeviceEventsParams) WithContext(ctx context.Context) *ListDeviceEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list device events params
func (o *ListDeviceEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list device events params
func (o *ListDeviceEventsParams) WithHTTPClient(client *http.Client) *ListDeviceEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list device events params
func (o *ListDeviceEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventName adds the eventName to the list device events params
func (o *ListDeviceEventsParams) WithEventName(eventName []string) *ListDeviceEventsParams {
	o.SetEventName(eventName)
	return o
}

// SetEventName adds the eventName to the list device events params
func (o *ListDeviceEventsParams) SetEventName(eventName []string) {
	o.EventName = eventName
}

// WithPage adds the page to the list device events params
func (o *ListDeviceEventsParams) WithPage(page *int64) *ListDeviceEventsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the list device events params
func (o *ListDeviceEventsParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the list device events params
func (o *ListDeviceEventsParams) WithPerPage(perPage *int64) *ListDeviceEventsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the list device events params
func (o *ListDeviceEventsParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WithUser adds the user to the list device events params
func (o *ListDeviceEventsParams) WithUser(user *string) *ListDeviceEventsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the list device events params
func (o *ListDeviceEventsParams) SetUser(user *string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *ListDeviceEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesEventName := o.EventName

	joinedEventName := swag.JoinByFormat(valuesEventName, "multi")
	// query array param event_name[]
	if err := r.SetQueryParam("event_name[]", joinedEventName...); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage int64
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}

	}

	if o.User != nil {

		// query param user
		var qrUser string
		if o.User != nil {
			qrUser = *o.User
		}
		qUser := qrUser
		if qUser != "" {
			if err := r.SetQueryParam("user", qUser); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
