name: Go CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Install go-swagger v0.27.0
      run: |
        swaggerdir=$(mktemp -d)
        cd "$swaggerdir"
        wget -O swagger https://github.com/go-swagger/go-swagger/releases/download/v0.27.0/swagger_linux_amd64
        chmod +x swagger
        echo "$swaggerdir" >> $GITHUB_PATH

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: build --snapshot

    - name: Test
      run: go test -v -race ./...

    - name: Test version command
      # we do NOT want to find ??? (hence the ! operator, defined in posix)
      run: "! ./dist/access-cli_linux_amd64/access-cli version | grep -q ???"

    - name: Lint
      run: go vet ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./dist/
