name: Compile release artifacts
on:
  release:
    types: [published]
jobs:
  build-release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
    - uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Install go-swagger v0.27.0
      run: |
        swaggerdir=$(mktemp -d)
        cd "$swaggerdir"
        wget -O swagger https://github.com/go-swagger/go-swagger/releases/download/v0.27.0/swagger_linux_amd64
        chmod +x swagger
        echo "$swaggerdir" >> $GITHUB_PATH

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
