// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PasswordChangeRequest password change request
// swagger:model PasswordChangeRequest
type PasswordChangeRequest struct {

	// current password
	CurrentPassword string `json:"current_password,omitempty"`

	// new password
	NewPassword string `json:"new_password,omitempty"`

	// password confirmation
	PasswordConfirmation string `json:"password_confirmation,omitempty"`
}

// Validate validates this password change request
func (m *PasswordChangeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PasswordChangeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PasswordChangeRequest) UnmarshalBinary(b []byte) error {
	var res PasswordChangeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
