// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SignInResponse sign in response
// swagger:model SignInResponse
type SignInResponse struct {

	// data
	Data *SignInResponseData `json:"data,omitempty"`
}

// Validate validates this sign in response
func (m *SignInResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SignInResponse) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SignInResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignInResponse) UnmarshalBinary(b []byte) error {
	var res SignInResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SignInResponseData sign in response data
// swagger:model SignInResponseData
type SignInResponseData struct {

	// allow password change
	AllowPasswordChange bool `json:"allow_password_change,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// image
	Image *string `json:"image,omitempty"`

	// last sign in at
	// Format: date-time
	LastSignInAt strfmt.DateTime `json:"last_sign_in_at,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// tenant id
	// Format: uuid
	TenantID strfmt.UUID `json:"tenant_id,omitempty"`

	// tenant name
	TenantName string `json:"tenant_name,omitempty"`

	// uid
	UID string `json:"uid,omitempty"`
}

// Validate validates this sign in response data
func (m *SignInResponseData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSignInAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTenantID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SignInResponseData) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(m.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("data"+"."+"email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SignInResponseData) validateLastSignInAt(formats strfmt.Registry) error {

	if swag.IsZero(m.LastSignInAt) { // not required
		return nil
	}

	if err := validate.FormatOf("data"+"."+"last_sign_in_at", "body", "date-time", m.LastSignInAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SignInResponseData) validateTenantID(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantID) { // not required
		return nil
	}

	if err := validate.FormatOf("data"+"."+"tenant_id", "body", "uuid", m.TenantID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SignInResponseData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignInResponseData) UnmarshalBinary(b []byte) error {
	var res SignInResponseData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
